CREATE OR REPLACE VIEW XXviewnameXX (NUM,TIMES, MEMBER, TYP,ID,DESC,VAL) AS
WITH NUMTTABLE (NUM,TID,TIMES,TYP) AS (
select rownumber() over (ORDER BY T.TID) AS NO, T.* FROM XXtablenameXX  T
),
NUMVTABLE (NUM,TID,TIMES,TYP,ID,VAL,MEMBER) AS (
  SELECT N.NUM,N.TID,N.TIMES,N.TYP,V.ID,V.VALUE,V.MEMBER FROM NUMTTABLE N, XXtablename1XX V WHERE N.TID = V.TID
)
SELECT N1.NUM,N2.TIMES,N2.MEMBER,N2.TYP,N2.ID,D.DESC,N2.VAL - N1.VAL FROM NUMVTABLE N1, NUMVTABLE N2, XXtablename2XX D WHERE N1.NUM + 1 = N2.NUM AND N1.ID = N2.ID AND N1.MEMBER = N2.MEMBER AND N2.ID = D.ID AND N2.VAL > N1.VAL
;

CREATE OR REPLACE VIEW XXviewsumXX (NUM,TIMES,MEMBER,ID,VAL) AS
 SELECT num,times,0 AS member,ID,SUM(VAL) AS val FROM XXviewnameXX WHERE MEMBER<>0  GROUP BY times,num,id  
;
 
